apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.client.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: playground-client
    app.kubernetes.io/part-of: playground
