apiVersion: v1
kind: Service
metadata:
  name: playground-client
  namespace: {{ .Values.namespace.name }}
  labels:
    app: playground-client
    app.kubernetes.io/part-of: playground
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: playground-client
  ports:
    - name: http
      port: {{ .Values.client.service.port }}
      targetPort: http
