apiVersion: v1
kind: Service
metadata:
  name: playground-server-http-canary
  namespace: {{ .Values.namespace.name }}
  labels:
    app: playground-server-http
    role: canary
    app.kubernetes.io/part-of: playground
spec:
  type: {{ .Values.http.service.type }}
  selector:
    app: playground-server-http
    role: canary
  ports:
    - name: http
      port: {{ .Values.http.service.port }}
      targetPort: http
