apiVersion: v1
kind: Service
metadata:
  name: playground-server-http-primary
  namespace: {{ .Values.namespace.name }}
  labels:
    app: playground-server-http
    role: primary
    app.kubernetes.io/part-of: playground
spec:
  type: {{ .Values.http.service.type }}
  selector:
    app: playground-server-http
    role: primary
  ports:
    - name: http
      port: {{ .Values.http.service.port }}
      targetPort: http
