apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.http.primary.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: playground-server-http
    role: primary
    app.kubernetes.io/part-of: playground