apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.http.canary.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: playground-server-http
    role: canary
    app.kubernetes.io/part-of: playground
